public class test55 { 
 public static void main(String args[]) { 
 try { 
 throw 10; 
 } 
 catch(int e) { 
 System.out.println("Catch the exception" + e); 
 } 
 } 
}